_wandb:
    value:
        cli_version: 0.22.2
        e:
            ugtxlmxujja0qqebghhy8ixnxpw5qec2:
                colab: https://colab.research.google.com/notebook#fileId=1EAdebEH1x_s-pFpKs6lwQEaQRSsFC2vx
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "45054410752"
                email: fecork88@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: b61444969f16561635cf7f0aa4b6527e609d5ca6
                    remote: https://github.com/fecork/parkinson-voice-uncertainty.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-8db92ee8-748f-85ae-4971-d89cf457b465
                host: 1d7c67491561
                memory:
                    total: "13605847040"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: cnn2d_training.ipynb
                python: CPython 3.12.12
                root: /content/drive/Othercomputers/ZenBook/parkinson-voice-uncertainty
                startedAt: "2025-10-30T19:42:08.969232Z"
                writerId: ugtxlmxujja0qqebghhy8ixnxpw5qec2
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.12
            "5": 0.22.2
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: Parkinson Voice
dense_units:
    value: 32
experiment_name:
    value: cnn2d_optuna_final_training
filters_1:
    value: 64
filters_2:
    value: 64
kernel_size_1:
    value: 6
kernel_size_2:
    value: 9
model_architecture:
    value: CNN2D
optimization:
    value: Optuna
p_drop_conv:
    value: 0.2
p_drop_fc:
    value: 0.5
plot_every:
    value: 5
save_plots:
    value: true
source:
    value: ibarra_2023_paper
use_wandb:
    value: true
