_wandb:
    value:
        cli_version: 0.22.2
        e:
            c6uym45nhjvgueebes5epbju6ri93uap:
                colab: https://colab.research.google.com/notebook#fileId=1EAdebEH1x_s-pFpKs6lwQEaQRSsFC2vx
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "253055008768"
                        used: "44993802240"
                email: fecork88@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: c5390b2b1e856dd099d2376c4ff5552bec0b4ff9
                    remote: https://github.com/fecork/parkinson-voice-uncertainty.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-dedc4f74-2687-6071-1bd7-bea732b051ac
                host: 989a72c50683
                memory:
                    total: "13605855232"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: cnn2d_training.ipynb
                python: CPython 3.12.12
                root: /content/drive/Othercomputers/ZenBook/parkinson-voice-uncertainty
                startedAt: "2025-10-31T20:24:47.122541Z"
                writerId: c6uym45nhjvgueebes5epbju6ri93uap
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "3":
                - 2
                - 13
            "4": 3.12.12
            "5": 0.22.2
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
