_wandb:
    value:
        cli_version: 0.22.2
        e:
            i9xnidh5ydznx3lq2bpfdp76eb0wvla9:
                colab: https://colab.research.google.com/notebook#fileId=1EAdebEH1x_s-pFpKs6lwQEaQRSsFC2vx
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "45620875264"
                email: fecork88@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: b61444969f16561635cf7f0aa4b6527e609d5ca6
                    remote: https://github.com/fecork/parkinson-voice-uncertainty.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-3b1d827e-e445-8c0c-bde7-bbdf9824eead
                host: 1af0715c681b
                memory:
                    total: "13605855232"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: cnn2d_training.ipynb
                python: CPython 3.12.12
                root: /content/drive/Othercomputers/ZenBook/parkinson-voice-uncertainty
                startedAt: "2025-10-30T16:53:33.458424Z"
                writerId: i9xnidh5ydznx3lq2bpfdp76eb0wvla9
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.12
            "5": 0.22.2
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: Parkinson Voice
dense_units:
    value: 32
early_stopping_patience:
    value: 15
experiment_name:
    value: cnn2d_optuna_final_training
filters_1:
    value: 32
filters_2:
    value: 64
gamma:
    value: 0.1
kernel_size_1:
    value: 6
kernel_size_2:
    value: 9
learning_rate:
    value: 0.1
model_architecture:
    value: CNN2D
momentum:
    value: 0.9
n_epochs:
    value: 100
optimization:
    value: Optuna
optimizer:
    value: sgd
p_drop_conv:
    value: 0.2
p_drop_fc:
    value: 0.5
plot_every:
    value: 5
save_plots:
    value: true
source:
    value: ibarra_2023_paper
step_size:
    value: 10
use_wandb:
    value: true
weight_decay:
    value: 0.0001
