_wandb:
    value:
        cli_version: 0.22.2
        e:
            qzuceognstjbuzf4gclo4mbu1dg62cue:
                codePath: test\demo_generic_wandb_training.py
                codePathLocal: test\demo_generic_wandb_training.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "998656958464"
                        used: "699797688320"
                email: fecork88@gmail.com
                executable: C:\Users\fecor\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 4ca74ea1b89bdd06a85ce5419f2641cfbb4a93f7
                    remote: https://github.com/fecork/parkinson-voice-uncertainty.git
                host: LAPTOP-JTCP4GUT
                memory:
                    total: "16856498176"
                os: Windows-10-10.0.26200-SP0
                program: C:\Proyectos\PHD- Parkinson - Incertidumbre - Prototipo\parkinson-voice-uncertainty\test\demo_generic_wandb_training.py
                python: CPython 3.10.3
                root: C:\Proyectos\PHD- Parkinson - Incertidumbre - Prototipo\parkinson-voice-uncertainty
                startedAt: "2025-10-29T20:38:26.818305Z"
                writerId: qzuceognstjbuzf4gclo4mbu1dg62cue
        m: []
        python_version: 3.10.3
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 105
            "2":
                - 1
                - 5
                - 35
                - 53
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.3
            "5": 0.22.2
            "8":
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
architecture:
    value: generic
epochs:
    value: 2
