_wandb:
    value:
        cli_version: 0.22.2
        e:
            szoihzpcxhsrdkike8bs8ap53pynciji:
                colab: https://colab.research.google.com/notebook#fileId=1EAdebEH1x_s-pFpKs6lwQEaQRSsFC2vx
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "253055008768"
                        used: "44994146304"
                email: fecork88@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: c5390b2b1e856dd099d2376c4ff5552bec0b4ff9
                    remote: https://github.com/fecork/parkinson-voice-uncertainty.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-13969af8-d0dc-e9e8-cf9c-18b51e157557
                host: 8df3ac1ec577
                memory:
                    total: "13605855232"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: cnn2d_training.ipynb
                python: CPython 3.12.12
                root: /content/drive/Othercomputers/ZenBook/parkinson-voice-uncertainty
                startedAt: "2025-11-01T17:38:23.211870Z"
                writerId: szoihzpcxhsrdkike8bs8ap53pynciji
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 105
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.12
            "5": 0.22.2
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: Parkinson Voice
dense_units:
    value: 32
experiment_name:
    value: cnn2d_optuna_final_training
filters_1:
    value: 64
filters_2:
    value: 64
kernel_size_1:
    value: 6
kernel_size_2:
    value: 9
model_architecture:
    value: CNN2D
optimization:
    value: Optuna
p_drop_conv:
    value: 0.2
p_drop_fc:
    value: 0.2
plot_every:
    value: 5
save_plots:
    value: true
source:
    value: ibarra_2023_paper
use_wandb:
    value: true
